-- demo-auth 初始化表结构（H2 + PostgreSQL 兼容）
-- GENERATED BY DEFAULT AS IDENTITY 在 H2 和 PostgreSQL 10+ 均可用

CREATE TABLE IF NOT EXISTS sys_user (
    zhdlxxbs        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dlzh            VARCHAR(64) NOT NULL UNIQUE,
    xm              VARCHAR(64),
    password_hash   VARCHAR(128) NOT NULL,
    sjh             VARCHAR(20),
    dzyx            VARCHAR(128),
    group_id        BIGINT NOT NULL DEFAULT 1,
    js              INT DEFAULT 2,
    zhzt            SMALLINT DEFAULT 1,
    scdl            SMALLINT DEFAULT 0,
    current_zone_id VARCHAR(64),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
